### PR TITLE
Code integration buffering revamp

### LINKED ISSUE #309: type . and crash still not fixed
Just got crashed typing . after a record variable.
Using Simba 1.1.0 (latest) and 64 bit.

Program exception! 
Stacktrace:

Exception class: EAccessViolation
Message: Access violation
  $000000000088EC24
  $00000000006A7DCF
  $00000000006A7DCF
  $00000000006A743F
  $0000000000686112
  $0000000000685484
  $000000000064C020
  $00000000006494DC
  $000000000063F619
  $0000000000597A24
  $0000000000594BE9
  $000000000055057D
  $000000000054D296
  $00007FF8852B2434
  $000000000042F533
  $000000000042FA02
  $000000000045979E
Simba Version: 1100

### PR DESCRIPTION
**Pull request by nielsAD**
Previously, multiple threads had access to IncludeBuffer; the critical
sections weren't doing anything. Removal from the Buffer caused
invalid references on other threads or in nested includes.

I have decided to maintain one buffer instead of thread local instances.
To maintain consistency, there's 1 critical section. This means that
only one thread can parse an include at a time (but other threads
can reuse the buffer afterwards).

To main consistency for nested includes, TCodeInsight now has a ref
counter. For external code, nothing changes. For CI code, make sure
to use DecRef() instead of Free() and call AddRef() when adding a
reference.

Includes are purged from the cache when not used frequently or
whenever the include file is touched (file age does not check
recursively yet).

Should fix #309.

### CODE REVIEW

File: Units/Misc/v_ideCodeInsight.pas [hunk 1]
```diff
@@ -140,45 +140,60 @@ function GetIncludeBuffer(out Buffer: TIncludeBuffer; FileName: string; LastChan
 var
   i, l: Integer;
 begin
-  l := High(IncludeBuffer);
+  // Should already be in critical section (!)
```
Comment (nielsAD) [inline Units/Misc/v_ideCodeInsight.pas]: Added these in for clarity and potential future use.

File: Units/Misc/v_ideCodeParser.pas [hunk 2]
```diff
@@ -526,24 +526,24 @@ function TDeclaration.GetCleanText: string;
...
+  s: string;
 begin
-  Result := '';
-  if (fCleanText <> '') then
-    Result := fCleanText
-  else if (fStartPos <> fEndPos) and (fOrigin <> nil) then
+  if (fCleanText = '') and (fStartPos <> fEndPos) and (fOrigin <> nil) then
   begin
-    fCleanText := RawText;
+    s := RawText;
```
Comment (nielsAD) [inline Units/Misc/v_ideCodeParser.pas]: These changes are to prevent race conditions. I think locking is overkill. In the rare case that two threads need this at the same time, just calculate it twice and store for future use.

**Comment by nielsAD** [comment]
Should ready for testing and merge :grinning:
